checks:
    php: true

tools:
    external_code_coverage: true

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'clover'