checks:
    php: true

tools:
    external_code_coverage: true

build:
    environment:
        php:
            version: "7.0"
            ini:
                'date.timezone': 'Europe/Berlin'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'clover'