cache:
  directories:
    - vendor

language: php

php:
    - 7.0
    - 7.1

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - phpunit --coverage-clover=clover.xml

after_script:
  - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_TOKEN" --format=php-clover clover.xml