cache:
  directories:
    - vendor

language: php

php:
    - 7

before_script:
    - wget -nc http://getcomposer.org/composer.phar
    - php composer.phar install
    - wget https://scrutinizer-ci.com/ocular.phar